* Servidor para controlar el vehículo teledirigido
Servidor creado con nodejs, express y socket.io para controlar un vehículo desde
un dispositivo remoto, haciendo uso de la aplicación para android.

** Iniciar el servicio web
Como con el servicio DHCP, este tambien se puede iniciar usando la =crontab= de
=root=.
#+begin_src conf
@reboot sleep 5 && npm --prefix /home/pi/develop/raspi_coche_webserver/ run start
#+end_src
* Servidor Control RC-Car
Servidor creado con nodejs y socket.io que acepta conexiones remotas para
manejar un coche teledirigido creado con Raspberry pi.

Para poder utilizar el coche desde cualquier dispositivo es recomendable
disponer de una interfaz WiFi que se pueda usar como punto de acceso, y seguir
los siguientes pasos.

1. Instalar dnsmasq y hostapd
   #+begin_src shell
   sudo apt install dnsmasq hostapd
   # Hay que detener los servicios
   sudo systemctl stop dnsmasq
   sudo systemctl stop hostapd
   #+end_src

2. Configurar una ip estática ~sudo nano /etc/dhcpcd.conf~ al final de este
   archivo añadimos, wlan0 aunque puede ser otra interface
   #+begin_src shell
   interface wlan0
   static ip_address=192.168.4.1/24
   nohook wpa_supplicant
   #+end_src
reiniciar el servicio dhcp y cargar la config de wlan0

3. Configurar el servidor DHCP (dnsmasq) editar el archivo /etc/dnsmasq.conf y
   añadir lo siguiente
   #+begin_src shell
   interface=wlan0
   dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
   #+end_src

y recargamos dnsmasq ~sudo systemctl reload dnsmasq~

4. Configurar el software de punto de acceso (hostapd) ~sudo nano
   /etc/hostapd/hostapd.conf~
   
   y añadir lo siguiente, ciertos parametro se pueden o deben cambiar. Y el
   nombre de la red y la contraseña no deben ser envueltas entre comillas.
   #+begin_src shell
   interface=wlan0
   driver=nl80211
   ssid=NameOfNetwork
   hw_mode=g
   channel=7
   wmm_enabled=0
   macaddr_acl=0
   auth_algs=1
   ignore_broadcast_ssid=0
   wpa=2
   wpa_passphrase=AardvarkBadgerHedgehog
   wpa_key_mgmt=WPA-PSK
   wpa_pairwise=TKIP
   rsn_pairwise=CCMP
   #+end_src

editamos el archivo del sistema que indica donde se encuentra esta información
~sudo nano /etc/default/hostapd~ Y la linea #DAEMON_CONF la reemplazamos con
esto ~DAEMON_CONF="/etc/hostapd/hostapd.conf"~ y activamos hostapd
#+begin_src shell
sudo systemctl unmask hostapd
sudo systemctl enable hostapd
sudo systemctl start hostapd
#+end_src

[[https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md][access-point raspberry]]
